##
## local costmap param, to be used with common costmap param
##

global_frame: /odom_combined
robot_base_frame: /base_footprint
update_frequency: 5.0
publish_frequency: 1.5

static_map: false
rolling_window: true
width: 6.0
height: 6.0
resolution: 0.025
origin_x: 0.0
origin_y: 0.0

inflation_radius: 0.15
publish_voxel_map: true

footprint: [[0.235,0.185],[-0.235,0.185],[-0.235,-0.185],[0.235,-0.185]]
obstacle_range: 2.5
raytrace_range: 3.0

plugins: 
#    - {name: static_wall_map,                  type: "costmap_2d::StaticLayer"}
#    - {name: static_admissable_obstacles_map,  type: "costmap_2d::StaticLayer"}
#    - {name: static_lethal_obstacles_map,      type: "costmap_2d::StaticLayer"}
    - {name: dynamic_obstacles_2d,             type: "costmap_2d::ObstacleLayer"}
#    - {name: hacked_dynamic_obstacles_3d,      type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,                  type: "costmap_2d::InflationLayer"}
    - {name: local_footprint,                 type: "costmap_2d::FootprintLayer"}
#    - {name: footprint,                        type: "costmap_2d::FootprintLayer"}
#    - {name: dynamic_obstacles_3d,             type: "costmap_2d::VoxelLayer"}

#static_wall_map:
#    unknown_cost_value: 0
#    lethal_cost_threshold: 100
#    map_topic: /map

#static_admissable_obstacles_map:
#    unknown_cost_value: 0
#    lethal_cost_threshold: 100
#    map_topic: /static_admissable_obstacles_map

#static_lethal_obstacles_map:
#    unknown_cost_value: 0
#    lethal_cost_threshold: 100
#    map_topic: /static_lethal_obstacles_map

dynamic_obstacles_2d:
     observation_sources: scan_filtered
     scan_filtered: { topic: /scan_filtered, sensor_frame: /laser, data_type: LaserScan,  clearing: true, marking: true, track_unknown_space: true}

dynamic_obstacles_3d:
     observation_sources: scan360_filtered
     scan360_filtered: { topic: /scan360_filtered, sensor_frame: /laser360, data_type: LaserScan,  clearing: true, marking: true, origin_z: 0.1 , z_resolution: 0.01, z_voxels: 120, unknown_threshold: 120, mark_threshold: 0, publish_voxel_map: true}
