controller_frequency: 0.3
controller_patience: 0.3
base_global_planner: global_planner/GlobalPlanner

#
# Global Planner
#

GlobalPlanner:
 visualize_potential: true
 publish_scale: 255

#
# Local Planner
#

TrajectoryPlannerROS:
  max_vel_x: 1.5 
  #0.5
  min_vel_x: 0.3 
  #0.1
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.5
  acc_lim_th: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: false
  yaw_goal_tolerance: 0.15
  xy_goal_tolerance: 0.15
  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  sim_time: 1.5
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.05

  vx_samples: 8
  vtheta_samples: 20
  dwa: true 
  #was false

#
# Recovery Behaviors
#

recovery_behaviors:
  - name: 'super_conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'move_slow_and_clear'
  #  type: 'move_slow_and_clear/MoveSlowAndClear'
  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'

super_conservative_reset:
  reset_distance: 5.0

conservative_reset:
  reset_distance: 3.0

aggressive_reset:
  reset_distance: 1.84

move_slow_and_clear:
  clearing_distance: 0.5
  limited_trans_speed: 0.25
  limited_rot_speed: 0.45
  limited_distance: 0.3

rotate_recovery:
  sim_granularity: 0.017
  frequency: 20.0
